//! Hand-written `Clone` for [`Config`].
//!
//! `#[derive(Clone)]` marks `clone` `#[inline]`, so every codegen unit and
//! every crate that clones a `Config` emits its own copy of this ~48 KiB
//! function: 17 copies in a release `openhuman-core`. `#[inline(never)]`
//! keeps exactly one. The struct literal lists every field, so adding a field
//! to `Config` without adding it here is a compile error, not a silent skip.

use super::config::Config;

impl Clone for Config {
    #[inline(never)]
    fn clone(&self) -> Self {
        Self {
            workspace_dir
action_dir
action_dir_override
files_dir_override
files_dir_history
config_path
cli_inference_snapshot
recovered_from_corruption
schema_version
api_url
api_key
inference_url
default_model
default_temperature
output_language
temperature_unsupported_models
dashboard
observability
autonomy
desktop
computer
hooks
privacy
sandbox
runtime
shell
web_chat
reliability
scheduler
scheduler_gate
agent
orchestrator
teams
context
model_routes
embedding_routes
cron
task_sources
channels_config
memory
composio
secrets
browser
http_request
curl
gitbooks
mcp_client
modules
capability_providers
multimodal
multimodal_files
seltz
searxng
web_search
search
proxy
cost
legacy_memory_sources
agent_registry
agents
local_ai
claude_agent_sdk
cloud_providers
primary_cloud
ephemeral_route
chat_provider
reasoning_provider
agentic_provider
coding_provider
vision_provider
memory_provider
embeddings_provider
custom_embeddings
node
runtime_python
runtime_pool
tokenjuice
hosting
voice_server
voice_providers
stt_provider
tts_provider
integrations
update
dictation
onboarding_completed
chat_onboarding_completed
model_registry: self.workspace_dir
action_dir
action_dir_override
files_dir_override
files_dir_history
config_path
cli_inference_snapshot
recovered_from_corruption
schema_version
api_url
api_key
inference_url
default_model
default_temperature
output_language
temperature_unsupported_models
dashboard
observability
autonomy
desktop
computer
hooks
privacy
sandbox
runtime
shell
web_chat
reliability
scheduler
scheduler_gate
agent
orchestrator
teams
context
model_routes
embedding_routes
cron
task_sources
channels_config
memory
composio
secrets
browser
http_request
curl
gitbooks
mcp_client
modules
capability_providers
multimodal
multimodal_files
seltz
searxng
web_search
search
proxy
cost
legacy_memory_sources
agent_registry
agents
local_ai
claude_agent_sdk
cloud_providers
primary_cloud
ephemeral_route
chat_provider
reasoning_provider
agentic_provider
coding_provider
vision_provider
memory_provider
embeddings_provider
custom_embeddings
node
runtime_python
runtime_pool
tokenjuice
hosting
voice_server
voice_providers
stt_provider
tts_provider
integrations
update
dictation
onboarding_completed
chat_onboarding_completed
model_registry.clone(),
        }
    }
}
